name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-go:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v4
      with:
        go-version: '1.22'
    - name: Run tests
      run: |
        go test ./...
    - name: Build
      run: |
        go build ./cmd/gittree

  test-rust:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Run tests
      run: |
        cargo test
    - name: Build
      run: |
        cargo build --release

  build-release:
    runs-on: ubuntu-latest
    needs: [test-go, test-rust]
    steps:
    - uses: actions/checkout@v4
    - name: Build Go binary
      run: |
        go build -o gittree-go ./cmd/gittree
    - name: Build Rust binary
      run: |
        cargo build --release
        cp target/release/gittree gittree-rs
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: binaries
        path: |
          gittree-go
          gittree-rs